language: node_js
node_js: node
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - npm install -g typescript
  - tsc
  - node out/index.js
  - git add include/*
  - ls
  - ls include
  - git checkout deploy
  - ls
  - ls include
  - git checkout master -- include/*
  - ls
  - ls include
  - git diff-index --quiet HEAD || git commit -m "CI Update"
  - git push https://${GIT_TOKEN}@github.com/roblox-ts/rbx-types.git deploy
