language: node_js
node_js: node
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

  - npm install -g typescript
  - tsc
  - node out/index.js

  - cd ..
  - mkdir deploy
  - cd deploy
  - git clone --depth=50 --branch=deploy https://github.com/roblox-ts/rbx-types.git roblox-ts/rbx-types
  - ls
  - cd rbx-types

  - cp ../../rbx-types/include/* include

  - git add -A
  - git status
  - git diff-index --quiet HEAD || git commit -m "CI Update"
  - git push https://${GIT_TOKEN}@github.com/roblox-ts/rbx-types.git deploy
