language: node_js
cache: npm
node_js:
  - "11"
branches:
  only:
    - master
    - deploy
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

  - npm install -g typescript
  - tsc

  - node out/index.js
  - |
    if ! git diff-index --quiet HEAD --; then
      git commit -m "Update generated files [skip ci]"
      git push https://${GIT_TOKEN}@github.com/roblox-ts/types.git master
    fi

  - npm run typedoc
  - |
    if ! git diff-index --quiet HEAD --; then
      git commit -m "Update typedocs [skip ci]"
      git push https://${GIT_TOKEN}@github.com/roblox-ts/types.git master
    fi

  - cd ..
  - git clone --depth=50 --branch=deploy https://github.com/roblox-ts/types.git deploy

  - ls
  - mkdir -p deploy/include
  - rm -rf deploy/include/*
  - cp -r types/include/* deploy/include
  - cp types/plugin.d.ts deploy/plugin.d.ts
  - cp types/README.md deploy/README.md
  - cd deploy

  - git add -A
  - git status
  - |
    if ! git diff-index --quiet HEAD --; then
      if [ "$TRAVIS_EVENT_TYPE" == "cron" ]; then
        git commit -m "Automatic Update"
      else
        git commit -m "Manual Update"
      fi
    fi
  - git push https://${GIT_TOKEN}@github.com/roblox-ts/types.git deploy
