language: node_js
node_js: node
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"
  - git checkout -b deploy
  - git pull
  - git checkout master include
  - npm install -g typescript
  - tsc
  - node out/index.js
  - git push https://${GIT_TOKEN}@github.com/roblox-ts/rbx-types.git
