language: node_js
node_js: node
script:
  - git config --global user.email "travis@travis-ci.org"
  - git config --global user.name "Travis CI"

  - npm install -g typescript
  - tsc
  - node out/index.js

  - cd ..
  - git clone --depth=50 --branch=deploy https://github.com/roblox-ts/rbx-types.git deploy

  - cp .rbx-types/include/* deploy/include
  - cd deploy

  - git add -A
  - git status
  - git diff-index --quiet HEAD || git commit -m "CI Update"
  - git push https://${GIT_TOKEN}@github.com/roblox-ts/rbx-types.git deploy
